trigger:
  - rebuild
pool:
  vmImage: ubuntu-latest
steps:
  - task: CmdLine@2
    displayName: Change to where website is stored
    inputs:
      script: |
        "cd ./Website\npwd\n"
  - task: NodeTool@0
    inputs:
      versionSpec: 10.x
    displayName: Install Node.js
  - script: |
      "npm install yarn\nyarn install\nyarn build\n"
    displayName: npm install and build
  - task: CopyFiles@2
    inputs:
      Contents: build/**
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: www
