name: Build and deploy Node.js app to Azure Web App - TechGlue
defaults:
      run:
        working-directory: ./Website

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: 'yarn install, build, and test'
        run: "npm install yarn\nyarn install  \nyarn build --if-present\n"
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .
  deploy:
    environment:
      name: Production
      url: '${{ steps.deploy-to-webapp.outputs.webapp-url }}'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
      - id: deploy-to-webapp
        name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: TechGlue
          package: .
          publish-profile: '${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0D92A5B421D9489390288A3A3B6B74A5
            }}'
          slot-name: Production
